import type { Metadata } from "next";
import "../ui/globals.css";
import { Navbar } from "@/ui/Navbar";
import { Footer } from "@/ui/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen flex flex-col justify-center">
        <Navbar />
        <main className="bg-red-500 flex flex-grow justify-center my-3">{children}</main>
        <Footer />  
      </body>
    </html>
  );
}
